### ISSUE TITLE
Aetheryte Link In Chat Fails when piping a Sonar message to Chat2

### ISSUE THREAD

**Issue by IsolatedRainbow** [horoscope-dev/Dalamud.Divination.AetheryteLinkInChat#19]
Hi there, 

Looks like Aetherye LIC fails to print to the Chat 2 window when using the Sonar plugin for Hunt and FATE tracking. It seems to pop with ChatBubbles, but doesn't print to the Chat 2 window.

**Comment by Diyagi** [comment]
```
03:58:41.434 | ERR Exception on OnChatMessage hook.
System.InvalidCastException: Unable to cast object of type 'Divination.AetheryteLinkInChat.AetherytePayload' to type 'Dalamud.Game.Text.SeStringHandling.Payloads.RawPayload'.
   at ChatTwo.Util.ChunkUtil.ToChunks(SeString msg, ChunkSource source, Nullable`1 defaultColour) in /work/repo/ChatTwo/Util/ChunkUtil.cs:line 67
   at ChatTwo.Store.ChatMessage(XivChatType type, UInt32 senderId, SeString sender, SeString message) in /work/repo/ChatTwo/Store.cs:line 366
   at Dalamud.Game.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter) in C:\goatsoft\companysecrets\dalamud\Game\Gui\ChatGui.cs:line 413
```
